### ISSUE TITLE
Hi I am Debanjan I saw that you r using my bot which is kind a nice. I don’t have any problem with it but kindly could you give some credit to the original author of the bot

### ISSUE THREAD

**Issue by Debanjan-San** [Deep-Eagle/DARK-ALFHA_V2#2]

**Comment by Deep-Eagle** [comment]
Ok I am your big fan I would like to work with you Karuna Kara can you give me your WhatsApp number

**Comment by Debanjan-San** [comment]
> Ok I am your big fan I would like to work with you Karuna Kara can you give me your WhatsApp number

Here is my number 917003213983

**Comment by Guru322** [comment]
_**UwU💖**_
